name: "cointegrated/rubert-tiny2"
problem_type: "single_label_classification"
torch_dtype: "float16" # Will be overridden based on hardware

peft_method: "lora" # либо можно другие: "lora", "adapter", "full"
