# defaults:
#   - data: labeling
#   - data: augmentation
#   - data: preprocessing
#   - model: labeling_model
#   - model: classification_model
#   - model: lora
#   - training: base
#   # - training: optimizer
#   # - training: callbacks
#   - inference: default
#   - _self_

defaults:
  - _self_
  - data: labeling
  # - labeling: labeling
  - model: labeling_model
  - training: base
  - inference: default

seed: 42
experiment_name: "review_classification"
version: "1.0.0"

paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  models: "models"
  results: "results"
  logs: "logs"
