categories:
  - "бытовая техника"
  - "обувь"
  - "одежда"
  - "посуда"
  - "текстиль"
  - "товары для детей"
  - "украшения и аксессуары"
  - "электроника"
  - "нет товара"

few_shot_examples:
  - review: "Заказали 14.10.2017 , получили 25.10.2017 \r\nНа мой размер 42, широкий как мешок. Надо было все таки размер  S заказать. \r\nПо поводу качества хороший пуховик. \r\nМех натуральный , съемный. \r\nБуду продавать ."
    category: "одежда"
  - review: "футболка хорошего качества,но футболка не как для девушек и женщин,а как на мужчину. она очень свободная. на свой М, заказала Л. теперь не знаю что делать,ибо она мне велика, даже моему папе она полезет."
    category: "одежда"
  - review: "Все отлично!!!"
    category: "нет товара"
  - review: "Рисунок не очень чёткий, а ткань прозрачная, видно нижнее бельё"
    category: "одежда"
  - review: "плохо!!!Низ рваный..деньги не вернули!Открыла спор,но его почему то закрыли"
    category: "нет товара"
  - review: "ткань - синтетика среднего качества, размерная сетка не соответствует действительности. Нитки не торчат. не пахнет. В общем за такие деньги более менее.. рекомендую брать на размер побольше."
    category: "одежда"
  - review: "на картинке  красиво в реалности третий сорт не брак"
    category: "нет товара"

file_names:
  train: "data/train.csv"
  test: "data/test.csv"
  labeled_train: "data/labeled_train.csv"
  augmented_train: "data/augmented_train.csv"
  test_predictions: "data/test_predictions.csv"

columns:
  text: "text"
  label: "label"
